### ISSUE TITLE
Change date

### ISSUE THREAD

**Issue by samcorcos** [Differential/meteor-blog#160]
How does one go about changing the date of a blog post? Usually, a `Post.update({...})` would do it, but I'm not familiar with how minimongoid implements this.

**Comment by coopermaruyama** [comment]
Since you mentioned minimongoid I'm going to assume you're trying to do this from the client. 

If doing it from the "edit post" page, the post's ID is available at `Session.get('postId')` so you can do `Post.first({_id: Session.get('postId') }).update({publishedAt: new Date() })`.  That will set it to now, for a custom date replace `new Date()` with any date object.

Also, if you just set a published post back to a draft, then back to published, it will update the date to the current date.

**Comment by samcorcos** [comment]
That did it! Thank you.
