### ISSUE TITLE
Does materialize css integrate with this package?

### ISSUE THREAD

**Issue by meichenblatt** [Differential/meteor-blog#188]
Does materialize css integrate with this package?

**Comment by hellogerard** [comment]
Not easily :-(

The best, proper way would probably be to create your own custom templates for everything, and ignore the package templates, so that you could fully integrate materialize.css. 

There might be a shortcut way where, using LESS, you re-use materialize.css styles on the package templates, but I'm not sure this is even easier.

I hope to completely rewrite the package templates to be more semantic and less opinionated as part of #82, which would make issue easier, but I have no timetable on it. Cheers.

**Comment by meichenblatt** [comment]
OK Thank you
