### ISSUE TITLE
Issue with Meteor-up deploy 

### ISSUE THREAD

**Issue by almogdesign** [Differential/meteor-blog#200]
I tried deploying to DO using Meteor up and ran into the following issue - https://github.com/arunoda/meteor-up/issues/566 

Once I removed the meteor blog package everything was fine I take there is some kind of conflict

**Comment by hellogerard** [comment]
Yeah, the issue is with the `vsivsi:file-collection` package, which uses its own (newer) version of the mongodb driver than the one meteor itself uses. I'm run into this problem before in similar situations. As much as I like that package, I think I might replace the library with a different one for gridFS uploads.

**Comment by almogdesign** [comment]
Let me know when it's fixed right now can't deploy the blog have you looked at https://github.com/CollectionFS/Meteor-CollectionFS

**Comment by almogdesign** [comment]
Any news regarding this ?
