### ISSUE TITLE
Cannot access blog data to create custom templates.

### ISSUE THREAD

**Issue by ggndpsingh** [Differential/meteor-blog#219]
I have the following config. There are two posts in the database but nothing shows when I try to create a custom template.

It works when i used the  {{> blogIndex}} template but I cant fetch the template context.
Configuration:
```
Blog.config({
    blogLayoutTemplate: 'blogLayout',
    blogIndexTemplate: 'myBlogIndex',
});
```
Template:
```
<template name="myBlogIndex">
    <div class="container">
        {{#each posts}}
            Title: {{title}}
        {{/posts}}
    </div>
</template>
```

**Comment by hellogerard** [comment]
Yeah, I think I am going to take this out.

So this was an earlier feature that was possible with Iron Router, since IR allows you to set the data context from the route. But Flow Router eschews this pattern (and I agree) and makes it very hard to do this (though still technically possible). I had to move all data logic to template-level subscriptions in order to support both routers.

I think I have to take this out, unless someone can think of a way to do this AND still support both routers. I agree it was a nice feature, and removing it greatly reduces the flexibility of meteor blog.

**Comment by hellogerard** [comment]
I am thinking the best way to provide blog post data is a mechanism similar to how Flow Router helps [with subscriptions](https://github.com/kadirahq/flow-router/#subscription-management), i.e. a helper that helps you with blog post subscriptions. It would work something like this:

```coffeescript
Template.onCreated ->
  Blog.subscribe()
  Tracker.autorun ->
    if Blog.ready()
      # do things that depend on blog posts
```

```html
<template name="myBlogIndexTemplate">
  {{#each posts}}
    Title: {{title}}
  {{else}}
    Loading...
  {{/each}}
</template>
```

Or

```html
<template name="myBlogIndexTemplate">
  {{#if blogReady}}
    {{#each posts}}
      Title: {{title}}
    {{/each}}
  {{else}}
    Loading...
  {{/if}}
</template>
```

WDYT?

**Comment by hellogerard** [comment]
Actually, I think I have a way to do this...
