### ISSUE TITLE
Images are saving as base64 also uploading to s3 

### ISSUE THREAD

**Issue by sasikanth513** [Differential/meteor-blog#277]
I have s3 configured and when I upload images using inline editor, Images are both uploading to s3 and also saving as base64 in inline.

In the display they are showing as base64 which makes the document heavy.

Anyone facing same issue?

**EDIT**

Here is a gif uploading image

http://g.recordit.co/9G2NYuuPcm.gif

image showing it is displaying base64

<img width="1273" alt="screen shot 2016-06-17 at 12 40 42 am" src="https://cloud.githubusercontent.com/assets/6153816/16129904/717d2a38-3424-11e6-820d-21d6a829719b.png">

and this is what saved in `'cfs.blog_s3Imports.filerecord'` collection

```
{
    "_id" : "AtZ8QXT2sNs7dQCjo",
    "original" : {
        "name" : "chaos_is_a_ladder_by_ertacaltinoz-d90nd4b.jpg",
        "updatedAt" : ISODate("2016-06-03T18:12:30.000Z"),
        "size" : 402550,
        "type" : "image/jpeg"
    },
    "uploadedAt" : ISODate("2016-06-16T19:10:04.582Z"),
    "copies" : {
        "blog_s3Imports" : {
            "name" : "chaos_is_a_ladder_by_ertacaltinoz-d90nd4b.jpg",
            "type" : "image/jpeg",
            "size" : 402550,
            "key" : "blog_s3Imports/AtZ8QXT2sNs7dQCjo-chaos_is_a_ladder_by_ertacaltinoz-d90nd4b.jpg",
            "updatedAt" : ISODate("2016-06-16T19:10:10.620Z"),
            "createdAt" : ISODate("2016-06-16T19:10:10.620Z")
        }
    }
}
```

**Comment by hellogerard** [comment]
It's been awhile since I've looked, but I believe this is a "optimistic UI" feature. The app needs the URL of the uploaded image before it can insert it into the body. But the URL is unknown until the image is uploaded. So the editor is inserting a base64-encoded version of the image, which is immediate and happens on the client, so the user can see the image while it uploads. If you save, and then refresh, I believe the base64 is replaced by the real URL.
